site_name: "Portfolio"
site_url: "https://kbertolo.github.io/"
site_description: "Portfolio do Kauan Bertolo"
site_author: "Kauan Bertolo"

docs_dir: "docs"

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized

extra_css:
  - https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/simple-icons/5.15.0/simple-icons.min.css
  - https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css
  - assets/css/lang-toggle.css

extra_javascript:
  - assets/js/lang-toggle.js

nav:
  - Home: "index.md"
  - Skills: "skills/skills.md"
  - About: "about.md"
