site_name: "Portfolio"
site_url: "https://kbertolo.github.io/"
site_description: "Kauan's Documentation"
site_author: "Kauan Bertolo"

docs_dir: "docs"

theme:
  name: cinder

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized
  - git-authors

extra_css:
  - https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/simple-icons/5.15.0/simple-icons.min.css
  - https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css

nav:
  - Seja Bem Vindo: "index.md"
  - Minhas Skills: "skills/skills.md"
  - Sobre: "about.md"